# Document clustering and topic modeling

## Set up environment

In [1]:
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [6]:
file = drive.CreateFile({'id':'192JMR7SIqoa14vrs7Z9BXO3iK89pimJL'})
file.GetContentFile('data.tsv')   

# Load data

In [7]:
import numpy as np
import pandas as pd
import nltk
import gensim

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
# Load data into dataframe
df = pd.read_csv('data.tsv', sep='\t', header=0, error_bad_lines=False)

b'Skipping line 8704: expected 15 fields, saw 22\nSkipping line 16933: expected 15 fields, saw 22\nSkipping line 23726: expected 15 fields, saw 22\n'
b'Skipping line 85637: expected 15 fields, saw 22\n'
b'Skipping line 132136: expected 15 fields, saw 22\nSkipping line 158070: expected 15 fields, saw 22\nSkipping line 166007: expected 15 fields, saw 22\nSkipping line 171877: expected 15 fields, saw 22\nSkipping line 177756: expected 15 fields, saw 22\nSkipping line 181773: expected 15 fields, saw 22\nSkipping line 191085: expected 15 fields, saw 22\nSkipping line 196273: expected 15 fields, saw 22\nSkipping line 196331: expected 15 fields, saw 22\n'
b'Skipping line 197000: expected 15 fields, saw 22\nSkipping line 197011: expected 15 fields, saw 22\nSkipping line 197432: expected 15 fields, saw 22\nSkipping line 208016: expected 15 fields, saw 22\nSkipping line 214110: expected 15 fields, saw 22\nSkipping line 244328: expected 15 fields, saw 22\nSkipping line 248519: expected 15 fields,

In [9]:
df.head()

marketplace  ...  review_date
0          US  ...   2015-08-31
1          US  ...   2015-08-31
2          US  ...   2015-08-31
3          US  ...   2015-08-31
4          US  ...   2015-08-31

[5 rows x 15 columns]

In [10]:
# Remove missing value
df.dropna(subset=['review_body'],inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 960056 entries, 0 to 960203
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   marketplace        960056 non-null  object
 1   customer_id        960056 non-null  int64 
 2   review_id          960056 non-null  object
 3   product_id         960056 non-null  object
 4   product_parent     960056 non-null  int64 
 5   product_title      960054 non-null  object
 6   product_category   960056 non-null  object
 7   star_rating        960056 non-null  int64 
 8   helpful_votes      960056 non-null  int64 
 9   total_votes        960056 non-null  int64 
 10  vine               960056 non-null  object
 11  verified_purchase  960056 non-null  object
 12  review_headline    960049 non-null  object
 13  review_body        960056 non-null  object
 14  review_date        960052 non-null  object
dtypes: int64(5), object(10)
memory usage: 117.2+ MB


In [15]:
# substract review_body as trainning set
data = df.loc[:, 'review_body'].tolist()

# Tokenizing and stemming

In [17]:
# Use nltk's English stopwords.
stopwords = nltk.corpus.stopwords.words('english')
stopwords.append("'s")
stopwords.append("'m")
stopwords.append("n't")
stopwords.append("br")

print ("We use " + str(len(stopwords)) + " stop-words from nltk library.")
print (stopwords[:20])

We use 183 stop-words from nltk library.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [19]:
from nltk.stem.snowball import SnowballStemmer
import re

stemmer = SnowballStemmer("english")

# tokenization and stemming
def tokenization_and_stemming(text):
    tokens = []
    # exclude stop words and tokenize the document, generate a list of string 
    for word in nltk.word_tokenize(text):
        if word.lower() not in stopwords:
            tokens.append(word.lower())

    filtered_tokens = []
    
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
            
    # stemming
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

In [20]:
tokenization_and_stemming(data[0])

['absolut',
 'love',
 'watch',
 'get',
 'compliment',
 'almost',
 'everi',
 'time',
 'wear',
 'dainti']

# TF-IDF

In [22]:
tfidf_model = TfidfVectorizer(max_df=0.99, max_features=1000,
                                 min_df=0.01, stop_words='english',
                                 use_idf=True, tokenizer=tokenization_and_stemming, ngram_range=(1,2))

tfidf_matrix = tfidf_model.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix.shape[0]) + \
      " reviews and " + str(tfidf_matrix.shape[1]) + " terms.")

In total, there are 960056 reviews and 411 terms.


In [23]:
# check the parameters
tfidf_model.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 0.99,
 'max_features': 1000,
 'min_df': 0.01,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': <function __main__.tokenization_and_stemming>,
 'use_idf': True,
 'vocabulary': None}

In [24]:
# words
tf_selected_words = tfidf_model.get_feature_names()

In [48]:
tf_selected_words[:10]

["'d",
 'abl',
 'absolut',
 'absolut love',
 'accur',
 'actual',
 'adjust',
 'ago',
 'alarm',
 'alreadi']

In [26]:
Eftfidf_matrix

<960056x411 sparse matrix of type '<class 'numpy.float64'>'
	with 12161247 stored elements in Compressed Sparse Row format>

#K means clustering

In [27]:
# k-means clustering
from sklearn.cluster import KMeans

num_clusters = 5

# number of clusters
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)

clusters = km.labels_.tolist()

In [34]:
product = { 'review': df[:].review_body, 'cluster': clusters}
frame = pd.DataFrame(product, columns = ['review', 'cluster'])

In [35]:
frame.head(10)

review  cluster
0  Absolutely love this watch! Get compliments al...        0
1       I love this watch it keeps time wonderfully.        0
2                                          Scratches        3
3  It works well on me. However, I found cheaper ...        3
4  Beautiful watch face.  The band looks nice all...        3
5  i love this watch for my purpose, about the pe...        0
6  for my wife and she loved it, looks great and ...        4
7  I was about to buy this thinking it was a Swis...        3
8  Watch is perfect. Rugged with the metal &#34;B...        4
9  Great quality and build.<br />The motors are r...        4

In [36]:
print ("Number of reviews included in each cluster:")
frame['cluster'].value_counts().to_frame()

Number of reviews included in each cluster:


cluster
3   636542
4   115873
0    95776
1    71673
2    40192

In [37]:
km.cluster_centers_

array([[0.00126937, 0.00207204, 0.02137691, ..., 0.00171569, 0.01176861,
        0.00680251],
       [0.00172826, 0.0017194 , 0.00143768, ..., 0.00207161, 0.00490479,
        0.00162052],
       [0.00066598, 0.00049239, 0.00041813, ..., 0.00074147, 0.00305293,
        0.00040923],
       [0.00440864, 0.00537962, 0.00499399, ..., 0.0043641 , 0.01905546,
        0.00401179],
       [0.0018309 , 0.00230686, 0.00440453, ..., 0.00289153, 0.01171859,
        0.00268264]])

In [38]:
km.cluster_centers_.shape

(5, 411)

In [39]:
print ("<Document clustering result by K-means>")

#km.cluster_centers_ denotes the importances of each items in centroid.
#We need to sort it in decreasing-order and get the top k items.
order_centroids = km.cluster_centers_.argsort()[:, ::-1] 

Cluster_keywords_summary = {}
for i in range(num_clusters):
    print ("Cluster " + str(i) + " words:", end='')
    Cluster_keywords_summary[i] = []
    for ind in order_centroids[i, :6]: #replace 6 with n words per cluster
        Cluster_keywords_summary[i].append(tf_selected_words[ind])
        print (tf_selected_words[ind] + ",", end='')
    print ()
    
    cluster_reviews = frame[frame.cluster==i].review.tolist()
    print ("Cluster " + str(i) + " reviews (" + str(len(cluster_reviews)) + " reviews): ")
    print (", ".join(cluster_reviews))
    print ()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



# Topic modeling-Latent dirichilet allocation

In [40]:
# Use LDA for clustering
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=5)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
# LDA requires integer values
tfidf_model_lda = CountVectorizer(max_df=0.99, max_features=500,
                                 min_df=0.01, stop_words='english',
                                 tokenizer=tokenization_and_stemming, ngram_range=(1,1))

tfidf_matrix_lda = tfidf_model_lda.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix_lda.shape[0]) + \
      " reviews and " + str(tfidf_matrix_lda.shape[1]) + " terms.")

In total, there are 960056 reviews and 355 terms.


In [42]:
# document topic matrix for tfidf_matrix_lda
lda_output = lda.fit_transform(tfidf_matrix_lda)
print(lda_output.shape)
print(lda_output)

(960056, 5)
[[0.02577426 0.0253714  0.89787495 0.02589161 0.02508778]
 [0.04159326 0.04068506 0.8365683  0.04087485 0.04027852]
 [0.10091865 0.59840914 0.10000113 0.10061433 0.10005674]
 ...
 [0.0337492  0.03359651 0.32025948 0.57886293 0.03353189]
 [0.94962853 0.01263307 0.01258087 0.01259939 0.01255814]
 [0.83255018 0.01867164 0.01833728 0.01860771 0.11183319]]


In [43]:
# topics and words matrix
topic_word = lda.components_
print(topic_word.shape)
print(topic_word)

(5, 355)
[[6.69970885e+03 9.16206696e+03 4.95247617e+02 ... 1.82911719e+03
  6.46071456e+03 7.22216334e+04]
 [2.62265043e+03 7.39052073e+03 2.34170038e+03 ... 3.06627920e+04
  9.15650958e+02 7.57097904e+02]
 [1.51779039e+02 3.86296606e+02 1.79015451e+04 ... 1.88111181e+02
  7.14239074e+02 8.75032723e+03]
 [6.23160020e+03 1.78810765e+03 6.38296546e+02 ... 4.84468634e+04
  4.00598071e+03 1.26219670e+04]
 [1.17526148e+03 2.55008056e+02 6.21031400e+00 ... 3.86831163e+04
  1.35041470e+03 2.99745005e+01]]


In [44]:
# column names
topic_names = ["Topic" + str(i) for i in range(lda.n_components)]

# index names
doc_names = ["Doc" + str(i) for i in range(len(data))]

df_document_topic = pd.DataFrame(np.round(lda_output, 2), columns=topic_names, index=doc_names)

# get dominant topic for each document
topic = np.argmax(df_document_topic.values, axis=1)
df_document_topic['topic'] = topic

df_document_topic.head(10)

Topic0  Topic1  Topic2  Topic3  Topic4  topic
Doc0    0.03    0.03    0.90    0.03    0.03      2
Doc1    0.04    0.04    0.84    0.04    0.04      2
Doc2    0.10    0.60    0.10    0.10    0.10      1
Doc3    0.74    0.03    0.17    0.03    0.03      0
Doc4    0.11    0.31    0.01    0.50    0.08      3
Doc5    0.03    0.03    0.40    0.51    0.03      3
Doc6    0.03    0.03    0.88    0.03    0.03      2
Doc7    0.52    0.41    0.03    0.03    0.03      0
Doc8    0.01    0.01    0.14    0.82    0.01      3
Doc9    0.58    0.02    0.35    0.02    0.02      0

In [45]:
df_document_topic['topic'].value_counts().to_frame()

topic
2  245359
3  242986
0  229354
4  144158
1   98199

In [46]:
# topic word matrix
print(lda.components_)
# topic-word matrix
df_topic_words = pd.DataFrame(lda.components_)

# column and index
df_topic_words.columns = tfidf_model_lda.get_feature_names()
df_topic_words.index = topic_names

df_topic_words.head()

[[6.69970885e+03 9.16206696e+03 4.95247617e+02 ... 1.82911719e+03
  6.46071456e+03 7.22216334e+04]
 [2.62265043e+03 7.39052073e+03 2.34170038e+03 ... 3.06627920e+04
  9.15650958e+02 7.57097904e+02]
 [1.51779039e+02 3.86296606e+02 1.79015451e+04 ... 1.88111181e+02
  7.14239074e+02 8.75032723e+03]
 [6.23160020e+03 1.78810765e+03 6.38296546e+02 ... 4.84468634e+04
  4.00598071e+03 1.26219670e+04]
 [1.17526148e+03 2.55008056e+02 6.21031400e+00 ... 3.86831163e+04
  1.35041470e+03 2.99745005e+01]]


'd          abl  ...        wrong          year
Topic0  6699.708850  9162.066958  ...  6460.714562  72221.633355
Topic1  2622.650433  7390.520732  ...   915.650958    757.097904
Topic2   151.779039   386.296606  ...   714.239074   8750.327227
Topic3  6231.600203  1788.107647  ...  4005.980709  12621.967014
Topic4  1175.261475   255.008056  ...  1350.414698     29.974500

[5 rows x 355 columns]

In [47]:
# print top n keywords for each topic
def print_topic_words(tfidf_model, lda_model, n_words):
    words = np.array(tfidf_model.get_feature_names())
    topic_words = []
    # for each topic, we have words weight
    for topic_words_weights in lda_model.components_:
        top_words = topic_words_weights.argsort()[::-1][:n_words]
        topic_words.append(words.take(top_words))
    return topic_words

topic_keywords = print_topic_words(tfidf_model=tfidf_model_lda, lda_model=lda, n_words=15)        

df_topic_words = pd.DataFrame(topic_keywords)
df_topic_words.columns = ['Word '+str(i) for i in range(df_topic_words.shape[1])]
df_topic_words.index = ['Topic '+str(i) for i in range(df_topic_words.shape[0])]
df_topic_words

Word 0 Word 1 Word 2   Word 3  ...  Word 11  Word 12  Word 13 Word 14
Topic 0  watch   time   work  batteri  ...     week     like   bought     new
Topic 1  watch   band   hand     link  ...      use     make     case     pin
Topic 2  watch   love  great     look  ...  perfect  husband  product     got
Topic 3  watch   look   like     nice  ...     easi    light    wrist    love
Topic 4   good  watch   look  qualiti  ...  product   expect  leather    size

[5 rows x 15 columns]

# Report

**Motivation:**

This project did clustering on customers' reviews about watches and applied LDA and KNN algorithms to build model to assign the review to its relative topic group.


**Step1: Text preprocessing**
* Exclude stop words and text tokenization(1&2 gram) using NLTK tools


**Step2: Feature engineering**
* Applied TF-IDF to transfer text into feature matrix


**Step3: Model training**
* 5 means clutsering was used to divide those comments into 5 groups
* Build LDA model to do clusterig and find the top keywords for each topic

